Update to 1.20.5

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,34 +10,32 @@ jobs:
     steps:
       - name: checkout repository
         uses: actions/checkout@v2
-      - name: setup jdk 17
-        uses: actions/setup-java@v1
+      - name: setup jdk 21
+        uses: actions/setup-java@v4
         with:
-          java-version: 17
+          distribution: temurin
+          java-version: 21
       # to cache gradle files
       - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/actions/setup-gradle@v3
         with:
-          cache-read-only: false
           gradle-home-cache-cleanup: true
-      - name: make gradle wrapper executable
-        if: ${{ runner.os != 'Windows' }}
-        run: chmod +x ./gradlecw
+          dependency-graph: generate-and-submit
+# Already needs to be executable, so the dirty check is correct
+#      - name: make gradle wrapper executable
+#        if: ${{ runner.os != 'Windows' }}
+#        run: chmod +x ./gradlecw
       - name: build
         run: ./gradlecw build
       - name: capture build artifacts
         uses: actions/upload-artifact@v2
         with:
           name: Artifacts
-          path: |
-            EntityCulling-Fabric/build/libs/*
-            EntityCulling-Forge/build/libs/*
-            EntityCulling-Neo/build/libs/*
-            EntityCulling-Versionless/build/libs/*
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: JUnit Tests
-          path: '**/build/test-results/test/TEST-*.xml'
-          reporter: java-junit        
+          path: 'versions/**/build/libs/*.jar'
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: JUnit Tests
+#          path: '**/build/test-results/test/TEST-*.xml'
+#          reporter: java-junit        
